### PR TITLE
Using custom cipher suite for Rackspace Cloud Databases service

### LINKED ISSUE #560: Smoke tests for Databases fail with SSL error
While trying to cut a new release, I ran all smoke tests. The Cloud Databases smoke tests immediately failed:

```
$ php tests/OpenCloud/Smoke/Runner.php --include=Database
Welcome to the PHP OpenCloud SmokeTest!

Authenticate
   Using identity endpoint: https://identity.api.rackspacecloud.com/v2.0/
   Using region: IAD
   Token generated: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Executing OpenCloud\Smoke\Unit\Database

   1. Get Flavors
PHP Fatal error:  Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 35: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure [url] https://iad.databases.api.rackspacecloud.com/v1.0/XXXXX/flavors/detail?limit=100' in /root/php-opencloud/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:359
```

### PR DESCRIPTION
**Pull request by ycombinator**
See https://github.com/rackspace/php-opencloud/issues/560#issuecomment-81790778.

Fixes #560 (temporarily).

### CODE REVIEW

File: lib/OpenCloud/Database/Service.php [hunk 1]
```diff
@@ -104,4 +106,24 @@ public function datastoreList($params = array())
...
+        // RC4 SSL cipher which is not supported by modern OpenSSL clients.
+        // Until the service can support additional, more modern and secure
+        // ciphers, this SDK has to ask curl to allow using the weaker
+        // cipher. For more information, see https://github.com/rackspace/php-opencloud/issues/560
+
+        $curlOptions = $client->getConfig()->get('curl.options');
+        $curlOptions['CURLOPT_SSL_CIPHER_LIST'] = CURL_SSLVERSION_TLSv1;
+        $client->getConfig()->set('curl.options', $curlOptions);
+
+        $client->getLogger()->critical('The SDK is using the TLSv1 cipher suite when connecting to the Rackspace Cloud Databases service. This suite contains a weak cipher (RC4) so please use at your own risk. See https://github.com/rackspace/php-opencloud/issues/560 for details.');
```
Comment (jamiehannaford) [inline lib/OpenCloud/Database/Service.php]: could we break up the text over multiple lines? (I think this is a PSR requirement) - we'll find out soon with the linter :)

Comment (ycombinator) [inline lib/OpenCloud/Database/Service.php]: Will do. Fixing.

File: tests/OpenCloud/Tests/Database/DatabaseTestCase.php [hunk 2]
```diff
@@ -37,4 +55,9 @@ public function setupObjects()
         $this->datastore = $this->service->datastore('10000000-0000-0000-0000-000000000001');
         $this->datastoreVersion = $this->datastore->version('b00000b0-00b0-0b00-00b0-000b000000bb');
     }
+
+    protected function assertCriticalMessageWasLogged()
+    {
+        $this->assertNotEmpty($this->getClient()->getLogger()->getCriticalLogMessage());
```
Comment (jamiehannaford) [inline tests/OpenCloud/Tests/Database/DatabaseTestCase.php]: yeah, this will do. another idea would be to use output buffering and actually check the stdout content [`ob-start`](http://php.net/manual/en/function.ob-start.php) and [`ob-get-contents`](http://php.net/manual/en/function.ob-get-contents.php)

Comment (ycombinator) [inline tests/OpenCloud/Tests/Database/DatabaseTestCase.php]: Do you want me to use output buffering or are you okay with the current mechanism?

**Comment by ycombinator** [comment]
@jamiehannaford: this is ready for review again, pending Travis build success.

**Comment by ycombinator** [comment]
Alright @jamiehannaford this is ready for review again.

File: lib/OpenCloud/Database/Service.php [hunk 3]
```diff
@@ -104,4 +105,36 @@ public function datastoreList($params = array())
...
+        $logMessage = 'The SDK is using a custom cipher suite when connecting '
+                    . 'to the Rackspace Cloud Databases service. This suite contains '
+                    . 'a weak cipher (RC4) so please use at your own risk. See '
+                    . 'https://github.com/rackspace/php-opencloud/issues/560 for details.';
+        $client->getLogger()->critical($logMessage);
+
+        $this->client = $client;
+    }
+
+    public static function getSslCipherList()
```
Comment (jamiehannaford) [inline lib/OpenCloud/Database/Service.php]: could we add donald's comment about what the string means as a docblock?

**Comment by jamiehannaford** [comment]
apart from the docblock thing, LGTM :+1:

File: lib/OpenCloud/Database/Service.php (hunk 3 above)
Comment (ycombinator) [inline lib/OpenCloud/Database/Service.php]: Is it okay if I add a link to Donald's comment (`https://github.com/rackspace/php-opencloud/issues/560#issuecomment-81790778`) in the docblock? I'm referencing the GitHub issue in other docblocks + the critical log message as well. The advantage of this is that the conversation in the GitHub issue provides more context than we could include inline in the code.

Comment (jamiehannaford) [inline lib/OpenCloud/Database/Service.php]: sure, that sounds good
