### PR TITLE
LB paginator fix

### LINKED ISSUE #502: LoadBalancer marker uses name instead of ID
### Summary

`\OpenCloud\Common\Collection\PaginatedIterator::constructNextUrl()` sets the wrong marker for Loadbalancers.

### Problem

I'm working with the `\OpenCloud\LoadBalancer\Service` class to retrieve a list of loadbalancers. The data that is returned is limited to 100 entries at once, so I'll have to set up processing to retrieve each new set.

Here's some initial code that I wrote to do this:

```php
$rax->setDatacenter('ord');
$client       = $rax->getClientByDatacenter();
$lbservice    = $client->loadBalancerService(null, $rax->getDatacenter());
$loadbalancer = $lbservice->loadBalancerList(true, array('limit' => 5));
echo "Found " . $loadbalancer->count() . " results" . PHP_EOL;

// Cycle through the loadbalancers
while ($loadbalancer->valid()) {
    echo "ID: " . $loadbalancer->currentElement()->id;
    echo " Name: " . $loadbalancer->currentElement()->name . PHP_EOL;
    $loadbalancer->next();
}

// Load the next set of Loadbalancers
$next_url = $loadbalancer->constructNextUrl();
echo "URL: " . $next_url . PHP_EOL;
$loadbalancer = $lbservice->resourceList('LoadBalancer', $next_url);
```
The `constructNextUrl()` method should be setting up the `marker` query argument to facilitate retrieving the next "page" of results. However, it seems that for loadbalancers the marker is set to the loadbalancer name when it should be the loadbalancer ID.

Here's the sample output from the above section of code (replacing IDs with ######):

```
Datacenter set to ORD
Found 5 results
ID: ###### Name: lbmaster-10004
ID: ###### Name: lbmaster-10004-ssl
ID: ###### Name: lbmaster-10006
ID: ###### Name: lbmaster-10006-ssl
ID: ###### Name: lbmaster-112
Getting new results ...
URL: https://ord.loadbalancers.api.rackspacecloud.com/v1.0/######/loadbalancers?limit=5&marker=lbmaster-112
Found 0 results
```
To test, I built the URL manually, and used that instead:

```php
$next_url->setQuery(array('limit' => 5, 'marker' => $loadbalancer->getElement(5-1)->id));
$loadbalancer = $lbservice->resourceList('LoadBalancer', $next_url);
```
With that change, I get the following output (again with IDs replaced by ######):

```
Datacenter set to ORD
Found 5 results
ID: ###### Name: lbmaster-10004
ID: ###### Name: lbmaster-10004-ssl
ID: ###### Name: lbmaster-10006
ID: ###### Name: lbmaster-10006-ssl
ID: ###### Name: lbmaster-112
Getting new results ...
URL: https://ord.loadbalancers.api.rackspacecloud.com/v1.0/######/loadbalancers?limit=5&marker=######
Found 5 results
ID: ###### Name: lbmaster-112
ID: ###### Name: lbmaster-112-ssl
ID: ###### Name: lbmaster-116
ID: ###### Name: lbmaster-116-ssl
ID: ###### Name: lbmaster-117
```

### Suggested solution

The code should be updated to utilize the loadbalancer ID instead of the loadbalancer name when generating the marker.

### PR DESCRIPTION
**Pull request by jamiehannaford**
Hopes to fix #502

### CODE REVIEW

**Comment by ycombinator** [comment]
@jamiehannaford I'll take a look at this later today but it looks like the Travis build failed due to the PSR-2 linter.

**Comment by jamiehannaford** [comment]
@ycombinator Fixed the linter stuff - also had to disable GB for 5.3 again :disappointed:

File: lib/OpenCloud/LoadBalancer/Collection/LoadBalancerIterator.php [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+    public function parseResponseBody($body)
+    {
+        $response = parent::parseResponseBody($body);
+
+        if (count($response) >= $this->getOption('limit.page')) {
+            // Save last element (we will need it for the next marker)
+            $this->nextElement = end($response);
+
+            // Since we previously asked for n+1 elements, pop the unwanted element
+            array_pop($response);
```
Comment (ycombinator) [inline lib/OpenCloud/LoadBalancer/Collection/LoadBalancerIterator.php]: Nit: You could combine this statement and the previous one into:

`$this->nextElement = array_pop($response)`.

File: lib/OpenCloud/LoadBalancer/Collection/LoadBalancerIterator.php [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+            reset($response);
```
Comment (ycombinator) [inline lib/OpenCloud/LoadBalancer/Collection/LoadBalancerIterator.php]: Nit: You could combine this statement and the previous two into:

`$this->nextElement = array_pop($response)`.

File: lib/OpenCloud/LoadBalancer/Service.php [hunk 3]
```diff
@@ -51,11 +52,20 @@ public function loadBalancer($id = null)
      */
     public function loadBalancerList($detail = true, array $filter = array())
     {
+        $options = $this->makeResourceIteratorOptions($this->resolveResourceClass('LoadBalancer'));
+
+        if (isset($filter['limit'])) {
+            $options['limit.page'] = $filter['limit'];
```
Comment (ycombinator) [inline lib/OpenCloud/LoadBalancer/Service.php]: Could you add a comment here explaining why this the next 2 statements are necessary? I'm particularly curious about the `unset`.

File: lib/OpenCloud/LoadBalancer/Service.php [hunk 4]
```diff
@@ -51,11 +52,20 @@ public function loadBalancer($id = null)
...
+            unset($filter['limit']);
+        }
+
         $url = $this->getUrl();
         $url->addPath(Resource\LoadBalancer::resourceName());
         $url->setQuery($filter);
 
-        return $this->resourceList('LoadBalancer', $url);
+        $options += array('baseUrl' => $url, 'key.marker' => 'id');
```
Comment (ycombinator) [inline lib/OpenCloud/LoadBalancer/Service.php]: Are you sure you want to use `+` here instead of `array_merge`? Asking because they treat key collisions differently. With `+`, elements from `$options` will be used in case of key collisions whereas with `array_merge`, elements from `array('baseUrl' => ...)` will be used in case of key collisions.

File: lib/OpenCloud/LoadBalancer/Collection/LoadBalancerIterator.php (hunk 2 above)
Comment (jamiehannaford) [inline lib/OpenCloud/LoadBalancer/Collection/LoadBalancerIterator.php]: :+1: good catch

File: lib/OpenCloud/LoadBalancer/Service.php (hunk 3 above)
Comment (jamiehannaford) [inline lib/OpenCloud/LoadBalancer/Service.php]: I guess they aren't needed. I was thinking of [these lines](https://github.com/rackspace/php-opencloud/blob/working/lib/OpenCloud/Common/Collection/PaginatedIterator.php#L275-L277) and wanted to have the iterator set the query value rather than couple it to the user's input. But thinking about it, it doesn't matter: either way the query is set and the URL will have the appropriate value.

Comment (ycombinator) [inline lib/OpenCloud/LoadBalancer/Service.php]: > either way the query is set and the URL will have the appropriate value.

How will the URL have the appropriate value without you explicitly setting `$options['limit.page']`? Is it part of the paginated "next page" URL returned in the API response?

File: lib/OpenCloud/LoadBalancer/Service.php (hunk 4 above)
Comment (jamiehannaford) [inline lib/OpenCloud/LoadBalancer/Service.php]: Yep but in this case the options are known to only contain a few keys (see [here](https://github.com/rackspace/php-opencloud/blob/working/lib/OpenCloud/Common/Base.php#L406-L416)) so I don't think there's a risk of collisions but I'll change anyway

Comment (jamiehannaford) [inline lib/OpenCloud/LoadBalancer/Service.php]: The base URL that is [passed in as an option](https://github.com/jamiehannaford/php-opencloud/blob/lb-paginator-fix/lib/OpenCloud/LoadBalancer/Service.php#L66) to the iterator is subsequently [used to construct next URLs](https://github.com/jamiehannaford/php-opencloud/blob/lb-paginator-fix/lib/OpenCloud/Common/Collection/PaginatedIterator.php#L272). If the query value is set on the initial URL, then it should still be set when the iterator constructs the next one.

**Comment by jamiehannaford** [comment]
@ycombinator Also, this is ready for another review :+1:

File: lib/OpenCloud/LoadBalancer/Service.php (hunk 3 above)
Comment (jamiehannaford) [inline lib/OpenCloud/LoadBalancer/Service.php]: The base URL that is [passed in as an option](https://github.com/jamiehannaford/php-opencloud/blob/lb-paginator-fix/lib/OpenCloud/LoadBalancer/Service.php#L66) to the iterator is subsequently [used to construct next URLs](https://github.com/jamiehannaford/php-opencloud/blob/lb-paginator-fix/lib/OpenCloud/Common/Collection/PaginatedIterator.php#L272). If the query value is set on the initial URL, then it should still be set when the iterator constructs the next one.

Comment (ycombinator) [inline lib/OpenCloud/LoadBalancer/Service.php]: Understood. Thanks.
